# Generated by Django 3.1 on 2020-08-22 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('director', models.CharField(blank=True, max_length=50)),
                ('producer', models.CharField(blank=True, max_length=50)),
                ('release_date', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('movie', models.ManyToManyField(related_name='people', to='movies.Movie')),
            ],
        ),
    ]
